export type ArtPiece = {
  src: string;
  /** Describes the piece for screen readers. Not shown on the page. */
  alt: string;
  /** Intrinsic size of the file in public/art — keeps the grid from shifting as images load. */
  width: number;
  height: number;
};

// Generated by `npm run art` from the contents of public/art.
// Alt text is preserved across runs — edit it here and it will survive.
export const artwork: ArtPiece[] = [
  {
    src: "/art/boat-at-anchor.jpg",
    alt: "Watercolour of a small white and yellow fishing boat on calm teal water, with hills behind and a golden reflection below.",
    width: 900,
    height: 1323,
  },
  {
    src: "/art/garden-in-bloom.jpg",
    alt: "Impressionist oil painting of a woman in a straw hat and pink blouse standing beside a bank of pink and white roses, with a pale sky behind.",
    width: 1240,
    height: 1400,
  },
  {
    src: "/art/lantern-and-rose.jpg",
    alt: "Painting of a glowing yellow lantern on a post at night, with a pink rose and dark green foliage beside it.",
    width: 933,
    height: 1400,
  },
  {
    src: "/art/path-to-the-beach.jpg",
    alt: "Painting of a sandy path through dune grass opening onto a deep blue sea under a bright sky with scattered clouds.",
    width: 1013,
    height: 1400,
  },
  {
    src: "/art/st-pauls.jpg",
    alt: "Tall narrow ink and watercolour study of St Paul's Cathedral in London, its dome and portico above a green tree.",
    width: 452,
    height: 1021,
  },
  {
    src: "/art/still-life-in-grey.jpg",
    alt: "Greyscale still life of a glass oil lamp, a metal teapot and a string of dark beads on a draped white cloth.",
    width: 1400,
    height: 1253,
  },
  {
    src: "/art/waterfall-study.jpg",
    alt: "Small landscape painting of a rocky waterfall spilling into a stream, framed by dense green trees and shrubs.",
    width: 1400,
    height: 1011,
  },
];
