/**
 * Keeps content/artwork.ts in step with whatever is in public/art.
 *
 *   npm run art
 *
 * For every image in public/art it will:
 *   - recompress it, but only if it busts the size budget (re-encoding an
 *     already-small JPEG just loses quality for nothing)
 *   - read its real dimensions
 *   - rewrite content/artwork.ts, keeping the alt text already written for
 *     files it has seen before
 *
 * Safe to run repeatedly. Delete a file and run it, and the entry goes too.
 */
import sharp from "sharp";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const ART_DIR = path.join(ROOT, "public/art");
const DATA_FILE = path.join(ROOT, "content/artwork.ts");

const MAX_EDGE = 1400;
const MAX_BYTES = 350 * 1024;
const QUALITY = 82;

const NEEDS_ALT = "TODO: describe this piece for screen readers";

function existingAlts() {
  const alts = new Map();
  if (!fs.existsSync(DATA_FILE)) return alts;
  const source = fs.readFileSync(DATA_FILE, "utf8");
  const re = /src:\s*"(\/art\/[^"]+)"[\s\S]*?alt:\s*("(?:[^"\\]|\\.)*")/g;
  let m;
  while ((m = re.exec(source))) alts.set(m[1], JSON.parse(m[2]));
  return alts;
}

const alts = existingAlts();

const files = fs
  .readdirSync(ART_DIR)
  .filter((f) => /\.(jpe?g|png|webp)$/i.test(f))
  .sort();

if (files.length === 0) {
  console.log("No images in public/art — the Artwork section will be hidden.");
}

const entries = [];
let recompressed = 0;

for (const file of files) {
  const full = path.join(ART_DIR, file);
  let meta = await sharp(full).metadata();
  let bytes = fs.statSync(full).size;

  const tooBig = Math.max(meta.width, meta.height) > MAX_EDGE;
  const tooHeavy = bytes > MAX_BYTES;

  if (tooBig || tooHeavy) {
    const before = bytes;
    const buf = await sharp(full)
      .rotate()
      .resize(MAX_EDGE, MAX_EDGE, { fit: "inside", withoutEnlargement: true })
      .jpeg({ quality: QUALITY, mozjpeg: true })
      .toBuffer();

    // Only keep the re-encode if it actually bought something. A file that is
    // already near the budget would otherwise be re-encoded on every run,
    // losing a little quality each time for no saving.
    if (tooBig || buf.length < bytes * 0.9) {
      fs.writeFileSync(full, buf);
      meta = await sharp(full).metadata();
      bytes = buf.length;
      recompressed++;
      console.log(
        `  compressed ${file}: ${(before / 1024).toFixed(0)}KB -> ${(bytes / 1024).toFixed(0)}KB, now ${meta.width}x${meta.height}`,
      );
    } else {
      console.log(
        `  ${file} is ${(bytes / 1024).toFixed(0)}KB — over budget but already well compressed, left alone`,
      );
    }
  }

  const src = `/art/${file}`;
  const alt = alts.get(src);
  if (!alt) console.log(`  NEW ${file} — add alt text in content/artwork.ts`);
  entries.push({
    src,
    alt: alt ?? NEEDS_ALT,
    width: meta.width,
    height: meta.height,
  });
}

const body = entries
  .map(
    (e) => `  {
    src: ${JSON.stringify(e.src)},
    alt: ${JSON.stringify(e.alt)},
    width: ${e.width},
    height: ${e.height},
  },`,
  )
  .join("\n");

fs.writeFileSync(
  DATA_FILE,
  `export type ArtPiece = {
  src: string;
  /** Describes the piece for screen readers. Not shown on the page. */
  alt: string;
  /** Intrinsic size of the file in public/art — keeps the grid from shifting as images load. */
  width: number;
  height: number;
};

// Generated by \`npm run art\` from the contents of public/art.
// Alt text is preserved across runs — edit it here and it will survive.
export const artwork: ArtPiece[] = [
${body}
];
`,
);

console.log(
  `\n${entries.length} image${entries.length === 1 ? "" : "s"}, ${recompressed} recompressed. Wrote content/artwork.ts`,
);
